# Utilise l'image officielle PostgreSQL comme image de base
FROM postgres:latest

# Créé l'App Directory
RUN mkdir -p /usr/app

# Copy directory
COPY ./ ./usr/app

# Pour PostgreSQL
RUN apt-get update && apt-get install -y postgresql-client cron

RUN chmod +x /usr/app/backup.sh

# Copie le fichier crontab dans le conteneur
COPY crontab.txt /etc/cron.d/db_backup_cron

# Démarre le service cron au démarrage du conteneur
RUN chmod 0644 /etc/cron.d/db_backup_cron

RUN crontab /etc/cron.d/db_backup_cron

RUN cron 