# Utilise l'image officielle PostgreSQL comme image de base
FROM postgres:latest

# Create App Directory
RUN mkdir -p /usr/app
WORKDIR /usr/app

# Copy directory
COPY . .

# Pour PostgreSQL
RUN apt-get update && apt-get install -y postgresql-client cron

RUN ls

RUN chmod +x crontab

# Copie le fichier crontab dans le conteneur
COPY crontab /etc/cron.d/db_backup_cron

# Démarre le service cron au démarrage du conteneur
CMD ["cron", "-f"]