version: '2'

services:
  db:
    container_name: db-container
    image: postgres
    restart: always
    build: ./api/db
    hostname: db
    env_file:
      - api/.env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./api/db:/usr/app

  backend:
    depends_on:
        - db
    container_name: backend-container
    image: backend
    build: ./api
    command: node server.js
    ports:
      - "8080:8080"
    volumes:
      - ./api:/usr/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always
    stdin_open: true
    tty: true

volumes:
  data: